### ISSUE TITLE
Configure metrics in Blinfold

### ISSUE THREAD

**Issue by Yorlmar** [Mark2Mark/Blindfold#1]
Hi Mark, for me only works over Cap Height and below the Baseline.
Is there any way to configure from what metric limit it can be used? for example over the x-Height, as you mentioned in the readme.md

It may be that I do not understood how to configure the plugin,
thanks for the support!

Yorlmar

**Comment by Mark2Mark** [comment]
Hi Yolmar,

did you try to use the context menu? Just right click anywhere on the canvas and it should give you the options »Blindfold Cap-Height« and »Blindfold x-Height«.

Let me know if it doesn’t work.

**Comment by Yorlmar** [comment]
Hi Mark,
it works perfectly, I did not know existed that option in the contextual menu. I appreciate the time for support and want to thank the effort on developing great plugins.

Yorlmar

**Comment by Mark2Mark** [comment]
Hi Yolmar, thanks for reporting and the kind words. You are very welcome. Also feel free to ask whenever you have an idea for improvements.
